apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    velero.io/exclude-from-backup: 'true'
  name: open-cluster-management:policy-hub-oauth
rules:
- apiGroups:
  - config.openshift.io/v1
  resources:
  - oauths
  verbs:
  - list
  - watch
